name: Build project

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      # Set up the rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-binutils and riscv32i-unknown-none-elf target
        run: |
          cargo install cargo-binutils
          rustup component add llvm-tools-preview
          rustup target add riscv32i-unknown-none-elf
      - name: Build project
        run: cargo build --release
